import subprocess
import os

# Define the LaTeX file
tex_file = "QIR_FINAL.tex"

# Ensure the file exists
if not os.path.exists(tex_file):
    print(f"❌ Error: {tex_file} not found.")
else:
    try:
        # Run pdflatex command to compile LaTeX to PDF
        subprocess.run(["pdflatex", "-interaction=nonstopmode", tex_file], check=True)

        # Cleanup auxiliary files generated by LaTeX
        aux_files = ["QIR_FINAL.aux", "QIR_FINAL.log", "QIR_FINAL.out"]
        for aux in aux_files:
            if os.path.exists(aux):
                os.remove(aux)

        print("✅ PDF successfully generated: QIR_FINAL.pdf")

    except subprocess.CalledProcessError:
        print("❌ Compilation failed. Check the LaTeX syntax.")
